services: 
  db:
    container_name: postgres_database
    image: postgres:14
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456


  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    user: '${UID}:${GID}'
    ports:
      - 8080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
      - PGADMIN_DEFAULT_PASSWORD=123456
